# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "centos7"
  config.vm.box_url = "https://github.com/vezzoni/vagrant-vboxes/releases/download/0.0.1/centos-7-x86_64.box"

  # GuestMachine1
  config.vm.define :guest1 do |guest1|

    guest1.vm.hostname = "guest1"
    guest1.vm.network :private_network, ip: "192.168.33.10", virtualbox__intnet: "intnet"
  end

  # GuestMachine2.
  config.vm.define :guest2 do |guest2|

    guest2.vm.hostname = "guest2"
    guest2.vm.network :private_network, ip: "192.168.33.20", virtualbox__intnet: "intnet"
  end
end

