# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "unisec/kali-linux"
  config.vm.box_version = "2017.1"

  config.vm.provision :shell, :inline => <<-EOT
    sudo apt-get -y update
    sudo apt-get -y upgrade
    sudo apt-get -y dist-upgrade
  EOT
end
