# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "centos7"
  config.vm.box_url = "https://github.com/vezzoni/vagrant-vboxes/releases/download/0.0.1/centos-7-x86_64.box"

  config.vm.define :docker do |docker|

    docker.vm.hostname = "docker"
    docker.vm.network :forwarded_port, guest: 80, host: 8080 
    docker.vm.provision "docker" do |d|
      d.run "nginx"
    end

  end
end

