# MySQLリポジトリを追加
- name: MySQL repo
  yum:
    name: http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm
    state: present

# MySQLをインストール
- name: MySQL Install
  yum:
    name: mysql-community-server
    state: present

# MySQLを起動
- name: MySQL start
  service:
    name: mysqld
    state: started
